### PR TITLE
My work on the frontend

### PR DESCRIPTION
**Pull request by CoryTsang**
Lots of files were changed and potential conflicts may arise from the changes.

### CODE REVIEW

**Comment by Katijino** [comment]
looking at the PR, i accepted the current changes and ran the code. Probably just an issue on my end, but can't seem to search anything.

**Comment by wrighs6** [comment]
It looks like there are some syntax errors in App,js that may have been caused by a manual merge

**Comment by CoryTsang** [comment]
Still in progress! DO NOT APPROVE

**Comment by CoryTsang** [comment]
Good for merge

**Review by wrighs6 — APPROVED** [review]

**Pull request merged**
